# Generated by Django 5.0.7 on 2024-07-27 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_withdraw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_withdraw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
