# Generated by Django 5.0.7 on 2024-07-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Total_earnings',
            new_name='total_earnings',
        ),
    ]
