# Generated by Django 5.0.7 on 2024-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isSuspended',
            field=models.BooleanField(default=False),
        ),
    ]
