# Generated by Django 5.0.7 on 2024-07-29 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=9, unique=True)),
                ('channel', models.CharField(blank=True, choices=[('BTC', 'BTC'), ('USDT', 'USDT'), ('ETH', 'ETH')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('deposit', 'DEPOSIT'), ('withdraw', 'WITHDRAW')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('approved', 'APPROVE'), ('declined', 'DECLINE'), ('pending', 'PENDING')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
