# Generated by Django 5.0.7 on 2024-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVE'), ('declined', 'DECLINE'), ('pending', 'PENDING')], default='pending', max_length=10),
        ),
    ]
